openapi: 3.0.0
info:
  title: Product Service
  description: Book store service
  version: 1.0.0

servers:
  - url: https://c176ziepa0.execute-api.eu-north-1.amazonaws.com
    description: AWS Lambda Proxy

tags:
  - name: Products

paths:
  /products:
    get:
      tags:
        - Products
      summary: Get list of available books
      responses:
        "200":
          description: Success response, returns list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Fails when unexpected error happened on server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - Products
      summary: Create productId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                  nullable: true
                price:
                  type: number
                count:
                  type: number
                  nullable: true
      responses:
        "201":
          description: Success response, returns created product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Fail when input data is invalid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductValidationError"
        "500":
          description: Fails when unexpected error happened on server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /products/{productId}:
    get:
      tags:
        - Products
      summary: Get book by id
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Success response, returns single product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Fails when no invalid uuid provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Fails when no product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Fails when unexpected error happened on server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number
    Error:
      type: object
      properties:
        message:
          type: string
        description:
          type: string
    FieldError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    CreateProductValidationError:
      type: object
      properties:
        message:
          type: string
        description:
          type: object
          properties:
            title:
              $ref: "#/components/schemas/FieldError"
            description:
              $ref: "#/components/schemas/FieldError"
            price:
              $ref: "#/components/schemas/FieldError"
            count:
              $ref: "#/components/schemas/FieldError"
